version: "3.8"
services:
  app:
    build: ./database/
    command: sh -c "sleep 10s ; python ./connect_db.py"
    depends_on:
      - "db"
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'cafe_app'
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  # adminer:
  #   image: adminer
  #   container_name: adminer_container
  #   restart: always
  #   ports:
  #     - 8080:8080
volumes:
  my_db:
